config/routes.rb
Rails.application.routes.draw do
  get "home/about" => "homes#about"
  devise_for :users, controllers: {
  	sessions: "users/sessions",
  	registrations: "users/registrations"
  }
  
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image

  validates :name, presence: true, length: {in: 2..20}
  validates :email, presence: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only:[:edit, :update]

	def index
		@user = User.find(current_user.id)
		@users = User.all
		@book = Book.new
	end

	def show
		@user = User.find(params[:id])
		@books = Book.where(user_id: @user.id)
		@book = Book.new
	end

	def edit
		@user = User.find(current_user.id)
	end

	def update
		@books = Book.all
		@book = Book.new
		@user = User.find(current_user.id)
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
		    redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end

	def correct_user
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(current_user.id)
		end	
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<div class="col-xs-3">
<% flash.each do |message_type, message| %>
<%= message %>
<% end %>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
	<h1>User info</h1>
	<%= attachment_image_tag @user, :profile_image, size: "90x90", format: "jpeg", class: "profile-thumb", fallback: "no_image.jpg" %>
	<table class="table">
		<tr>
			<th width=100%>name</th>
			<th><%= @user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
	</table>
	<%= link_to edit_user_path(@user.id) do %>
	<span class="glyphicon glyphicon-wrench btn btn-default btn-block sidebtn"></span>
	<% end %>
	<h2>New book</h2>
	<%= form_for(book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title,class: "submit" %>
	<h4>Opinion</h4>
	<%= f.text_area :body, class: "submit" %>
	<%= f.submit "Create Book", class: "btn btn-primary submit2" %>	
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count ,"error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<div class="col-xs-4">
	<h1>User info</h1>
		<%= form_for(@user) do |u| %>
		<%= u.label :Name %>
		<%= u.text_field :name %>
		<h4>Image</h4>
		<%= u.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
		<%= u.label :introduction, class: "intro" %>
		<%= u.text_area :introduction, class: "intro" %>
		<%= u.submit "Update User", class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
<%= render "users/sidebar", book: @book %>
<div class="col-xs-9">
<h1>Users</h1>
	<table class="table">
		<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	    </thead>
	    <tboddy>
		<% @users.each do |u| %>
		<tr>
			<th><%= attachment_image_tag u, :profile_image, size: "25x25",fallback: "no_image.jpg" %></th>
			<th><%= u.name %></th>
			<th><%= link_to "Show", user_path(u.id) %></th>
		</tr>
		<% end %>
	    </tboddy>
	</table>
</div>

app/views/users/show.html.erb
<div class="row">
<%= render "users/sidebar", book: @book %>
<div class="col-xs-9">
	<h1>Books</h1>
	<table class="table table-hover">
		<thead>
		<tr class="table-borderless">
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
		</thead>
		<tbody>
		<% @books.each do |b| %>
		<tr>
			<th><%= link_to user_path(@user.id) do %>
				<%= attachment_image_tag @user, :profile_image, size: "25x25",fallback: "no_image.jpg" %>
				<% end %></th>
			<th><%= link_to book_path(b.id) do%>
				<%= b.title %>
			</th>
			<% end %>
			<th><%= b.body %></th>
		</tr>
		<% end %>
		</tbody>
	</table>
</div>
</div>