config/routes.rb
Rails.application.routes.draw do
  get "home/about" => "homes#about"
  devise_for :users, controllers: {
  	sessions: "users/sessions",
  	registrations: "users/registrations"
  }
  
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, length: {in: 1..200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_book_user, only:[:edit, :update]

	def index
		@books = Book.all
		@book = Book.new
		@user = User.find(current_user.id)
	end

	def show
		@book = Book.find(params[:id])
		@book_new = Book.new
		@user = User.find(@book.user_id)
	end

	def new
		@book = Book.new
	end

	def create
		@user = User.find(current_user.id)
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "You have creatad book successfully."
		    redirect_to book_path(@book.id)
		else
			render action: :index
		end	
	end

	def edit
		@user = User.find(current_user.id)
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		
		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."
		    redirect_to book_path(@book.id)
		else
			render action: :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body, :user_id)
	end
	def correct_book_user
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<div class="row">
	<div class="col-xs-9">
		<h1 class="text-center">Editing Book</h1>
		<%= form_for(@book) do |b| %>
		<h4>Title</h4>
		<%= b.text_field :title , class: "edit-btn" %>
		<h4>Opinion</h4>
		<%= b.text_area :body, class: "edit-btn" %>
		<%= b.submit "Update Book", class: "btn btn-primary edit-btn" %>
		<% end %>
		<%= link_to "Show", book_path(@book.id) %>
    	<p class="edit-1">|</p>
    	<%= link_to "Back", books_path %>
	</div>
</div>

app/views/books/index.html.erb
<div class="row">
<%= render "users/sidebar", book: @book %>

<div class="col-xs-9">
	<h1>Books</h1>
	<table width=100% class="table">
		<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
		</thead>
		<tbody>
		<% @books.each do |b| %>
		<tr>
			<th><%= link_to user_path(b.user_id) do %>
				<%= attachment_image_tag b.user, :profile_image, size: "25x25", fallback: "no_image.jpg" %>
			</th>
            <% end %>
			<th><%= link_to book_path(b.id) do %>
				<%= b.title %>
		    </th>
		    <% end %>
			<th><%= b.body %></th>
		</tr>
		<% end %>
	    </tbody>
	</table>
</div>
</div>

app/views/books/show.html.erb
<div class="row">
<%= render "users/sidebar", book: @book_new %>

<div class="col-xs-9">
	<h1>Book detail</h1>
	<table class="table">
	  <tr>
		<th><%= link_to user_path(@user.id) do %>
			<%= attachment_image_tag @user, :profile_image, size: "30x30", fallback: "no_image.jpg" %>
			<br>
			<%= @book.user.name %>
		</th>
		    <% end %>
		<th>
			<%= link_to book_path(@book.id) do %>
			<%= @book.title %>
		</th>
		    <% end %>
		<th><%= @book.body %></th>
		<% if @book.user_id == current_user.id %>
		<th><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></th>
		<th><%= link_to "Destroy", book_path(@book.id), class: "btn btn-danger", method: :delete, data: {confirm:"本当に消去しますか？"} %></th>
		<% end %>
	  </tr>
	  </table> 
</div>