config/routes.rb
Rails.application.routes.draw do
  get "home/about" => "homes#about"
  devise_for :users, controllers: {
  	sessions: "users/sessions",
  	registrations: "users/registrations"
  }
  
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <header class="navbar navbar-inverse">
      <div class="container">
        <span class="header-text">Bookers</span>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
        <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %></li>
        <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %></li>
        <li><%= link_to "logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", "/", class: "glyphicon glyphicon-home" %></li>
        <li><%= link_to "About", "/home/about", class: "glyphicon glyphicon-link" %></li>
        <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
        <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
      </ul> 
  <% end %>
  </div> 
  </header>
  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
  <footer>
    <div class="container">
    <small class="footer-text">CopyRight Infratop.inc</small>
    </div>
  </footer>
</html>